Fix Random not working for trivial group
gap-packages/polycyclic pull request #62
Opened 2021-05-14 18:46 UTC by sTertooy

Fixes #59.

2021-05-14 23:11 UTC, fingolfin requested changes
Thank you!

I'd prefer if this was done very slightly differently. If you are willing to follow my suggestion, that'd be awesome; otherwise, I'll take care of it later

2021-05-14 23:11 UTC, fingolfin commented on gap/basic/pcpgrps.gi
> +    else
```suggestion
    if Length( pcp ) = 0 then
        return One( G );
    fi;
```
I would prefer if you just inserted this check, and then left the rest of the function unchanged: Besides reducing the diff (and avoiding issues with incorrect indentation as in the next line), IMHO every level of nesting makes code harder to understand.

2021-05-15 12:05 UTC, sTertooy commented
Should be fixed now :)

2021-05-15 12:07 UTC, fingolfin approved these changes
Thanks!

2021-05-15 12:08 UTC, merged